version: 2

jobs:
  # Build & Deploy against development backend
  # TODO: Rename once the workflows are properly configured
  build:
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker

      # Loading the previous build from the cache.
      - restore_cache:
          key: dev-docker-image-{{ checksum "package-lock.json" }}
      - run: set +o pipefail docker load -i /caches/app.tar | true

      # Building.
      - run: docker build --build-arg ENV=development -t $DEV_AWS_ACCOUNT_ID.dkr.ecr.$DEV_AWS_REGION.amazonaws.com/community-app:$CIRCLE_SHA1 .

      # Updating the cache.
      - run: mkdir -p /caches && docker save -o /caches/app.tar $DEV_AWS_ACCOUNT_ID.dkr.ecr.$DEV_AWS_REGION.amazonaws.com/community-app:$CIRCLE_SHA1
      - save_cache:
          key: dev-docker-image-{{ checksum "package-lock.json" }}
          paths:
            - /caches/app.tar

      # Deployment.
      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli --upgrade --user
      - deploy:
          command: ./deploy.sh DEV $CIRCLE_SHA1

  # Test job for the cases when we do not need deployment. It just rapidly
  # installs (updates) app dependencies, and runs tests (ESLint, Stylelint,
  # Jest unit-tests).
  test:
    docker:
      - image: circleci/node:8.2.1
    steps:
      - checkout
      - restore_cache:
          key: test-node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: test-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

#    docker:
#      - image: circleci/node:8.2.1
#    steps:
#      - checkout
#      - restore_cache:
#          key: node_modules__{{ checksum "package-lock.json" }}
#      - run: npm install
#      - save_cache:
#          key: node_modules__{{ checksum "package-lock.json" }}
#          paths:
#            - node_modules
#      - run: npm test
#      - run: npm run build

#    pre:
#      - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
#    docker:
#      - image: circleci/node:8.2.1
#    services:
#      - docker
#    post:
#      - docker version
#    steps:
#      - checkout
#      - run: sudo apt-get install libyaml-dev libpython2.7-dev
#      - run: sudo pip install 'awsebcli==3.7.4' --force-reinstall
#      - run: npm install
#      - deploy:
#          branches:
#            only: develop
#          commands:
#            - docker build --build-arg BUILD_ENV=development -t $DEV_AWS_ACCOUNT_ID.dkr.ecr.$DEV_AWS_REGION.amazonaws.com/community-app:$CIRCLE_SHA1 .
#            - ./deploy.sh DEV $CIRCLE_SHA1

#    tags:
#      only: /v[0-9]+(\.[0-9]+)*/
          
#    steps:
#      - deploy:
#        commands:
#          - docker build --build-arg BUILD_ENV=production -t $PROD_AWS_ACCOUNT_ID.dkr.ecr.$PROD_AWS_REGION.amazonaws.com/community-app:$CIRCLE_TAG .
#          - ./deploy.sh PROD $CIRCLE_TAG

#    general:
#      artifacts:
#        - ./__coverage__
