version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.2.1
    steps:
      - checkout
      - restore_cache:
          key: node_modules_{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node_modules_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
#    pre:
#      - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
#    docker:
#      - image: circleci/node:8.2.1
#    services:
#      - docker
#    post:
#      - docker version
#    steps:
#      - checkout
#      - run: sudo apt-get install libyaml-dev libpython2.7-dev
#      - run: sudo pip install 'awsebcli==3.7.4' --force-reinstall
#      - run: npm install
#      - deploy:
#          branches:
#            only: develop
#          commands:
#            - docker build --build-arg BUILD_ENV=development -t $DEV_AWS_ACCOUNT_ID.dkr.ecr.$DEV_AWS_REGION.amazonaws.com/community-app:$CIRCLE_SHA1 .
#            - ./deploy.sh DEV $CIRCLE_SHA1

#    tags:
#      only: /v[0-9]+(\.[0-9]+)*/
          
#    steps:
#      - deploy:
#        commands:
#          - docker build --build-arg BUILD_ENV=production -t $PROD_AWS_ACCOUNT_ID.dkr.ecr.$PROD_AWS_REGION.amazonaws.com/community-app:$CIRCLE_TAG .
#          - ./deploy.sh PROD $CIRCLE_TAG

#    general:
#      artifacts:
#        - ./__coverage__
